server:
  # TODO: change to your application's port number
  port: 4550

management:
  security:
    enabled: false

spring:
  application:
    name: HMCTS Rhubarb Recipes Service
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DATABASE}?sslmode=${POSTGRES_SSL_MODE:require}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD:}
    properties:
      charSet: UTF-8
    maxWaitForConnection: 2000
    minSize: 8
    maxSize: 32
    evictionInterval: 10000
    minIdleTime: 1 minute
    checkConnectionWhileIdle: true
    checkConnectionOnReturn: true
    removeAbandoned: true
    removeAbandonedTimeout: 60
    abandonWhenPercentageFull: 0
    testOnBorrow: true
    validationQuery: SELECT 1

