server:
  # TODO: change to your application's port number
  port: 4550

spring:
  application:
    name: HMCTS Rhubarb Recipes Service
  config:
    import: "optional:configtree:/mnt/secrets/plumsi/,optional:configtree:/mnt/secrets/crumblesi/,optional:configtree:/mnt/secrets/toffee/"
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DATABASE:plum}?sslmode=${POSTGRES_SSL_MODE:require}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD:}
    properties:
      charSet: UTF-8
    maxWaitForConnection: 2000
    minSize: 8
    maxSize: 32
    evictionInterval: 10000
    minIdleTime: 1 minute
    checkConnectionWhileIdle: true
    checkConnectionOnReturn: true
    removeAbandoned: true
    removeAbandonedTimeout: 60
    abandonWhenPercentageFull: 0
    testOnBorrow: true
    validationQuery: SELECT 1

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: "/"
  security:
    enabled: false
