name: crumble-recipe-backend
home: https://github.com/hmcts/cnp-plum-recipes-service
version: 0.0.3
description: This is for Jenkins pipeline tests of plum /crumble app.
maintainers:
  - name: HMCTS CNP Team
    email: cnpteam@hmcts.net
