name: crumble-recipe-backend
apiVersion: v1
home: https://github.com/hmcts/cnp-plum-recipes-service
version: 0.1.2
description: This is for Jenkins pipeline tests of plum /crumble app.
maintainers:
  - name: HMCTS CNP Team
    email: cnpteam@hmcts.net
